spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: yourMailAddres
    password: yourPersonalMailCode
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
